"use client";

import dynamic from "next/dynamic";
import { Tab, AnalysisResult } from "@/types";
import { useState, useEffect } from "react";
import { useAnalyze } from "@/hooks/useAnalyze";
import UploadForm from "@/components/UploadForm";
import ResultTabs from "@/components/ResultTabs";
import { colors, fonts, radius, spacing, gradients } from "@/styles/tokens";
import { useSession, signOut } from "next-auth/react";
import { useRouter } from "next/navigation";

const DownloadReport = dynamic(() => import("@/components/DownloadReport"), {
  ssr: false,
});

function CopyButton({ result }: { result: AnalysisResult }) {
  const [copied, setCopied] = useState(false);

  function handleCopy() {
    const summary = `
🎯 PathForge Learning Pathway Summary

Missing Skills: ${result.skill_gap.missing_skills.join(", ")}

Recommended Courses:
${result.pathway.map((c, i) => `${i + 1}. ${c.course} (${c.level} · ⭐${c.rating})`).join("\n")}

⏱️ Hours Saved: ${result.impact.hours_saved}h (${result.impact.efficiency_gain_percent}% more efficient)
📊 Grounding Score: ${result.grounding.total_grounded}/${result.grounding.total_recommended} courses verified

Generated by PathForge — AI Onboarding Engine
    `.trim();

    navigator.clipboard.writeText(summary);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <button
      className="w-full sm:w-auto"
      style={{
        padding: "10px 24px",
        background: "transparent",
        border: `1px solid ${colors.border}`,
        borderRadius: radius.md,
        color: copied ? colors.accent : colors.textMuted,
        fontFamily: fonts.body,
        fontSize: 14,
        cursor: "pointer",
        transition: "all 0.2s",
      }}
      onClick={handleCopy}
    >
      {copied ? "✓ Copied!" : "⎘ Copy Summary"}
    </button>
  );
}

function Logo() {
  return (
    <div style={{ position: "relative", display: "flex", alignItems: "center", justifyContent: "center", width: 36, height: 36, borderRadius: 10, background: gradients.accent, boxShadow: "0 6px 16px rgba(255,90,54,0.3)", flexShrink: 0 }}>
      <span style={{ fontSize: 18, color: "#fff", fontWeight: 800 }}>⬡</span>
    </div>
  );
}

export default function Home() {
  const { loading, loadingStep, error, result, analyze, reset } = useAnalyze();
  const [activeTab, setActiveTab] = useState<Tab>("gap");
  const [menuOpen, setMenuOpen] = useState(false);
  const { status } = useSession();
  const router = useRouter();

  useEffect(() => {
    const style = document.createElement("style");
    style.innerHTML = `@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');`;
    document.head.appendChild(style);
  }, []);

  function handleAnalyze(params: Parameters<typeof analyze>[0]) {
    if (status !== "authenticated") {
      router.push("/login?callbackUrl=/");
      return;
    }
    analyze(params);
  }

  return (
    <div style={s.page}>
      <div className="noise-overlay" />
      <div className="aurora-1" style={{ top: "-260px", left: "-260px" }} />
      <div className="aurora-2" style={{ bottom: "-320px", right: "-320px" }} />

      <header style={s.header} className="glass px-4 py-3 sm:px-8 md:px-12">
        <div style={s.logoRow}>
          <Logo />
          <div style={{ display: "flex", flexDirection: "column", gap: 0 }}>
            <span style={s.logoText} className="text-base sm:text-xl">PathForge</span>
            <span style={s.logoSub} className="hidden sm:block">AI-Adaptive Onboarding Engine</span>
          </div>
        </div>

        <nav style={s.nav} className="hidden md:flex">
          <a href="/resume-builder" style={s.navLink}>
            Resume Builder
          </a>
          <a href="#start" style={s.navLink}>
            How It Works
          </a>
        </nav>

        <div className="hidden sm:flex" style={{ alignItems: "center", gap: 14 }}>
          {status === "authenticated" ? (
            <button
              onClick={() => signOut({ callbackUrl: "/" })}
              style={{ ...s.loginLink, background: "none", border: "none", cursor: "pointer", fontFamily: fonts.body }}
            >
              Logout
            </button>
          ) : (
            <a href="/login" style={s.loginLink}>Login</a>
          )}
          <a href="#start" style={s.headerCta}>Get Started</a>
        </div>

        <button
          className="flex sm:hidden"
          aria-label="Toggle menu"
          onClick={() => setMenuOpen((v) => !v)}
          style={{
            alignItems: "center", justifyContent: "center",
            width: 36, height: 36, borderRadius: radius.md,
            border: `1px solid ${colors.border}`, background: "transparent",
            fontSize: 18, color: colors.textPrimary,
          }}
        >
          {menuOpen ? "✕" : "☰"}
        </button>
      </header>

      {menuOpen && (
        <div
          className="flex sm:hidden flex-col"
          style={{
            position: "relative", zIndex: 9, gap: 4,
            padding: "12px 20px 20px",
            borderBottom: `1px solid ${colors.border}`,
            background: colors.bg,
          }}
        >
          <a href="/resume-builder" style={s.navLink} onClick={() => setMenuOpen(false)}>Resume Builder</a>
          <a href="#start" style={s.navLink} onClick={() => setMenuOpen(false)}>How It Works</a>
          {status === "authenticated" ? (
            <button
              onClick={() => { setMenuOpen(false); signOut({ callbackUrl: "/" }); }}
              style={{ ...s.navLink, background: "none", border: "none", textAlign: "left", cursor: "pointer", padding: 0, fontFamily: fonts.body }}
            >
              Logout
            </button>
          ) : (
            <a href="/login" style={s.navLink} onClick={() => setMenuOpen(false)}>Login</a>
          )}
          <a href="#start" style={{ ...s.headerCta, textAlign: "center", marginTop: 8 }} onClick={() => setMenuOpen(false)}>Get Started</a>
        </div>
      )}

      {!result ? (
        <UploadForm
          onAnalyze={handleAnalyze}
          loading={loading}
          loadingStep={loadingStep}
          error={error}
        />
      ) : (
        <main style={s.results} className="animate-fadeIn px-4 sm:px-6 py-8 sm:py-10">
          <div style={s.summary} className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4">
            <Pill label="Skills You Have"     value={result.skill_gap.resume_skills.length} delay={0} />
            <Pill label="Skills Missing"      value={result.skill_gap.missing_skills.length} danger delay={1} />
            <Pill label="Courses Recommended" value={result.pathway.length} accent delay={2} />
            <Pill
              label="Grounding Score"
              value={`${result.grounding.total_grounded}/${result.grounding.total_recommended}`}
              accent
              delay={3}
            />
          </div>

          {result.skill_gap.missing_skills.length === 0 ? (
            <div
              className="px-4 sm:px-6"
              style={{
                textAlign: "center",
                paddingTop: 60, paddingBottom: 60,
                background: colors.surface,
                border: `1px solid ${colors.border}`,
                borderRadius: radius.xxl,
                marginBottom: 32,
              }}
            >
              <div style={{ fontSize: 48, marginBottom: 16 }}>🎉</div>
              <h2 style={{
                fontFamily: fonts.display,
                fontSize: 24, fontWeight: 700,
                color: colors.accent, marginBottom: 8,
              }}>
                Perfect Match!
              </h2>
              <p style={{ color: colors.textMuted, fontSize: 16 }}>
                Your resume already covers all the required skills for this role.
                No additional training needed.
              </p>
            </div>
          ) : (
            <ResultTabs result={result} activeTab={activeTab} onTabChange={setActiveTab} />
          )}

          <div className="flex flex-col sm:flex-row" style={{ gap: 12, marginTop: 32 }}>
            <button style={s.backBtn} className="w-full sm:w-auto" onClick={reset}>← New Analysis</button>
            <CopyButton result={result} />
            <DownloadReport result={result} />
          </div>
        </main>
      )}
    </div>
  );
}

function Pill({ label, value, danger, accent, delay = 0 }: {
  label: string;
  value: number | string;
  danger?: boolean;
  accent?: boolean;
  delay?: number;
}) {
  return (
    <div
      className="hover-lift card-animated-border"
      style={{
        ...s.pill,
        ...(danger ? s.pillDanger : {}),
        ...(accent ? s.pillAccent : {}),
        animation: `cardEntrance 0.5s ease ${delay * 0.1}s both`,
      }}
    >
      <span style={s.pillLabel}>{label}</span>
      <span
        className="text-xl sm:text-3xl"
        style={{
          ...s.pillValue,
          ...(accent ? { background: gradients.accent, WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" } : {}),
          ...(danger ? { color: colors.danger } : {}),
        }}
      >
        {value}
      </span>
    </div>
  );
}

const s: Record<string, React.CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: colors.bg,
    fontFamily: fonts.body,
    color: colors.textPrimary,
    position: "relative",
    overflowX: "hidden",
  },
  header: {
    position: "sticky", top: 0, zIndex: 10,
    display: "flex", alignItems: "center",
    justifyContent: "space-between",
    borderBottom: `1px solid ${colors.border}`,
    flexWrap: "wrap",
  },
  logoRow: { display: "flex", alignItems: "center", gap: 12, minWidth: 0 },
  logoText: {
    fontFamily: fonts.display,
    fontWeight: 800,
    color: colors.textPrimary,
    letterSpacing: "-0.5px",
    lineHeight: 1.2,
    whiteSpace: "nowrap",
  },
  logoSub: {
    fontSize: 11, color: colors.textMuted,
    letterSpacing: "0.04em",
    whiteSpace: "nowrap",
  },
  nav: {
    alignItems: "center", gap: 32,
  },
  navLink: {
    fontSize: 15, color: colors.textSub,
    textDecoration: "none", fontWeight: 500,
    fontFamily: fonts.body,
  },
  loginLink: {
    fontSize: 15, color: colors.textPrimary,
    textDecoration: "none", fontWeight: 500,
  },
  headerCta: {
    padding: "10px 20px",
    background: gradients.accent,
    color: "#fff",
    borderRadius: radius.md,
    fontSize: 14, fontWeight: 700,
    textDecoration: "none",
    boxShadow: "0 6px 16px rgba(255,90,54,0.25)",
    whiteSpace: "nowrap",
  },
  results: {
    position: "relative", zIndex: 1,
    maxWidth: 960, margin: "0 auto",
  },
  summary: {
    marginBottom: spacing.xxl,
  },
  pill: {
    minWidth: 0,
    background: colors.surface,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: "16px 20px",
    display: "flex", flexDirection: "column", gap: spacing.xs,
    cursor: "default",
    transition: "all 0.3s ease",
    boxShadow: "0 2px 12px rgba(20,20,30,0.04)",
  },
  pillDanger: {
    borderColor: colors.borderDanger,
    background: "rgba(220,38,38,0.04)",
  },
  pillAccent: {
    borderColor: "rgba(255,90,54,0.25)",
    background: colors.accentBg,
  },
  pillLabel: {
    fontSize: 12, color: colors.textMuted,
    textTransform: "uppercase", letterSpacing: "0.05em",
  },
  pillValue: {
    fontFamily: fonts.display,
    fontWeight: 800, color: colors.textPrimary,
  },
  backBtn: {
    background: "transparent",
    border: `1px solid ${colors.border}`,
    color: colors.accent, padding: "8px 20px",
    borderRadius: radius.md, cursor: "pointer",
    fontFamily: fonts.body, fontSize: 14,
    transition: "all 0.2s ease",
  },
};
